### ISSUE TITLE
WinRM -SQL Server DB Deployment can't find SqlPackage.exe

### ISSUE THREAD

**Issue by ttutko** [Microsoft/vsts-rm-extensions#104]
I installed the Data-Tier Application Framework using the August 2016 x86 and x64 msi's as well as the version linked in the readme (July 2015) but the powershell script is unable to find SqlPackage.exe. It appears that the registry settings created/updated by the installers put information in: 
    `"HKLM\SOFTWARE\Wow6432Node\Microsoft\Microsoft SQL Server\Data-Tier Application Framework"`

The script in the extension, however, is looking for a key called "DACFramework" instead of "Data-Tier Application Framework".

**Comment by mvvsubbu** [comment]
Hi Thanks for bringing it to our notice. Can you float PR if you have already fixed it for you?

**Comment by mvvsubbu** [comment]
I assume you are unblocked your self by using the dac framework installation link given in the readme. Can you please confirm

**Comment by ttutko** [comment]
I used the installation links in the readme to begin with and that's when I received the error. I unblocked myself by hard coding the correct path into the Powershell script provided but I have not had time to go back and try and fix the powershell to work for all scenarios for a pull request.

**Comment by mvvsubbu** [comment]
Thanks for confirming we are addressing this soon.

**Comment by mvvsubbu** [comment]
Issue is fixed with 1.3.0 version release of the extension https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp. Closing the issue please feel free to re-open it if still face any issues

**Comment by DaveKLloyd** [comment]
I am running version 1.3.9 and we are getting the error:
"Deployment failed on machine <SERVER> with following message : System.Exception: Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine <SERVER> Is this new or the same as above.
