### ISSUE TITLE
Support Deployment of Sub-Applications / Virtual Directories

### ISSUE THREAD

**Issue by sumo300** [Microsoft/vsts-rm-extensions#106]
In many cases, applications we deploy are not root applications.  They are hosted as sub-applications underneath a single site.  It'd be great if the WinRM tasks directly supported this scenario.  We're currently trying to find a combination of arguments to pass in to make it work, trying to avoid custom tasks.

**Comment by mvvsubbu** [comment]
Thanks for your feedback adding our PM @RoopeshNair  to note this feedback

**Comment by RoopeshNair** [comment]
We have in our backlog to support the deployment of virtual applications. 
For now, please refer to GitHub link: https://github.com/Microsoft/vsts-rm-extensions/issues/56 which has more details around this.
