### ISSUE TITLE
"Site '.' does not exist" error

### ISSUE THREAD

**Issue by LordCheese** [Microsoft/vsts-rm-extensions#113]
I've been trying to set up a TFS 2015 (on-prem) build definition to deploy an ASP.NET Core 1.0.1 (using .NET Framework 4.6.2, not pure Core), however it always fails on the Deploy IIS App step. The previous step is a Manage IIS App step to ensure the site is set up correctly, and that works fine. When it gets into the Deploy step, it fails with the error:

    Error Code: ERROR_SITE_DOES_NOT_EXIST

This is connecting from the build server to IIS running on a Server 2012 R2 VM hosted in Azure. 

I've attached the verbose log from the task: [IIS Deploy task log.txt](https://github.com/Microsoft/vsts-rm-extensions/files/498559/IIS.Deploy.task.log.txt)

The deployment step is configured as:
![image](https://cloud.githubusercontent.com/assets/2198696/18918747/0268a2d6-8559-11e6-97bb-b93e51e7e921.png)

Production.xml (not optimally named, but that's a minor problem right now): 

    <parameters>
        <parameter name="IIS Web Application Name" defaultValue="QuoteOrderDev" tags="IisApp" />
    </parameters>

I've also tested manually importing the deployment package into IIS, and that worked fine, so I don't believe it's an issue with the deployment package.

This is the final step that I seem to be stuck on. Everything else has been working great, including ensuring that the site is set up correctly (and exists) in the IIS Manage App task.

**Comment by mvvsubbu** [comment]
Have you confirmed the website exists ? And what is the result of the following command when ran on your azure VM

"C:\Program Files\IIS\Microsoft Web Deploy V3\msDeploy.exe"  -verb:sync -source:package="C:\code-staging\quote-order-dev\publish.zip"  -setParamFile="C:\code-staging\quote-order-dev\production.xml" -setParam:name="IIS Web Application Name",value="QuoteOrderDev" -enableRule:DoNotDeleteRule -enableRule:AppOffline -dest:auto -retryAttempts:3 -retryInterval:3000

**Comment by luke-austin** [comment]
Had a similar issue passing additional arguments to MSDeploy seemed to fix it for me

`-setParam:kind=ProviderPath,scope=contentPath,value=$(target.website)`

Of course replacing $(target.website) with your website name.

**Comment by mvvsubbu** [comment]
Can you confirm the above solution worked for you or not?

**Comment by LordCheese** [comment]
Hi @mvvsubbu,

I just tried your suggestion, and I get the same error: 
![image](https://cloud.githubusercontent.com/assets/2198696/19315782/4a862698-905c-11e6-8da4-1a9ed878fdbd.png)

**Comment by mvvsubbu** [comment]
Actually we haven't tested this extension Asp.Net Core Apps yet, I wanted to check the error is coming from MsDeploy only. Given that Luke's suggestion helped you I will recommend for anyone if they hit same issue in future until officially make this extension ready for Asp.Net Core Apps ::

**Comment by Igor1306** [comment]
> Had a similar issue passing additional arguments to MSDeploy seemed to fix it for me
> 
> `-setParam:kind=ProviderPath,scope=contentPath,value=$(target.website)`
> 
> Of course replacing $(target.website) with your website name.

Thank you so much !
