### ISSUE TITLE
IIS Web App Deploy task doesn't work with iisApp provider

### ISSUE THREAD

**Issue by shamnigurat** [Microsoft/vsts-rm-extensions#120]
The [issue #115](https://github.com/Microsoft/vsts-rm-extensions/issues/115) was closed incorrectly.
Without fixing this issue as I mentioned deployment is not working at all and the task "WimRM - IIS Web App Deployment" becomes almost useless.
Just look at the parameters of the "WinRM - IIS Web App Deployment" task.
There is the parameter named "Website Name". Just tell me: what is this parameter for?
The information's hint tells: "Provide the name of the website for deploying the Web project to."
But this parameter is not used while deploying to IIS so I can't deploy as the hint tells me!
Furthermore, just imagine the case: I have zipped web-package (msdeploy) and want to deploy it to IIS. All I know is the name of the web site to deploy - how can I deploy in this case (I don't know the physical path of the web site and I don't need it because I would like to deploy to differnet environments with the same site's name!)? The "Override Parameters" doesn't work for this purpose even if I set 'name="IIS Web Application Name",value="...."' - msdeploy just tries to unpack the content of the web-package to the physical path the package was created from. It's absolutely unacceptable because the web-package content must be deployed to the physical path of the site.

**Comment by mvvsubbu** [comment]
Can you sync over face to face call? Can you propose your convenient time, so that we can discuss and understand more about it

**Comment by shamnigurat** [comment]
Sorry, I can't sync over face to face call. But it's simple to describe the bug here:

**1)** Download the web-package file [WebApp.zip](https://github.com/Microsoft/vsts-rm-extensions/files/526441/WebApp.zip) to your IIS-machine. The file was created by the following command:

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:iisApp="O:\TestSite" -dest:package="WebApp.zip" -declareParam:name="IIS Web Application Name",defaultValue="WebApp" -replace:match="O:\\TestSite",replace="WebApp" -verb:sync -retryAttempts:20 -disableRule:BackupRule

**2)** Create the site named "DestinationSite" on your IIS.

**3)** Run the following command (on your IIS-machine):

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="WebApp.zip" -setParam:name="IIS Web Application Name",value="DestinationSite" -enableRule:AppOffline -dest:auto -retryAttempts:3 -retryInterval:3000

You will get the following result (I hope your IIS-machine doesn't have the disk "O:" - any way you get the point):
**Error Code: ERROR_SITE_DOES_NOT_EXIST
More Information: Site 'O:' does not exist.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_SITE_DOES_NOT_EXIST.
Error count: 1.**

**4)** "Magic" part - just run the following command:

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="WebApp.zip" -enableRule:AppOffline -dest:iisApp="DestinationSite" -retryAttempts:3 -retryInterval:3000

You will be wondered but the result is:
**Info: Adding file (DestinationSite\test.html).
Total changes: 1 (1 added, 0 deleted, 0 updated, 0 parameters changed, 7 bytes copied)**

What the miracle! ;)

I gave you hints in the [issue #115](https://github.com/Microsoft/vsts-rm-extensions/issues/115) how to fix the bug.
Even more, this is the fixed script: [MsDeployOnTargetMachines.zip](https://github.com/Microsoft/vsts-rm-extensions/files/526444/MsDeployOnTargetMachines.zip) (it's working without any issues in my environment).

**Comment by mvvsubbu** [comment]
The way you are creating package is different from our recommendation. You refer the following link for detailed help : https://www.visualstudio.com/en-us/docs/release/examples/other-servers/net-to-vm 

If you  want to create package from visual studio you can follow : https://codemonkeygotsmarts.wordpress.com/2014/04/21/msdeploy-create-a-web-deployment-package-from-visual-studio/

**Comment by mvvsubbu** [comment]
Any update?

**Comment by mvvsubbu** [comment]
Can i assume your issue is resolved?

**Comment by shamnigurat** [comment]
As I can see you read my last post casually and really don't understand the purpose of the "WinRM - IIS Web App Deployment" task and how it should work.
I don't know how else I could argue here because I'VE EXPOSED THE BUG IN STEP BY STEP INSTRUCTION!!! I don't know what else do you want from me and wonder why you are responsible for this code!!! Read the following carefully:

1) "_The way you are creating package is different from our recommendation. You refer the following link for detailed help_"

First of all, point me the exact paragraph of the manual that describes the process of WEB-PACKAGE CREATION - you even can try Ctrl-F key combination for the word 'package' ;).
Secondly, what do you mean by "our recommendation"??? If it's not the MANDATORY RULE then "WinRM - IIS Web App Deployment" task MUST work as I described earlier.
Thirdly, as I can see you don't understand how the msdeploy.exe works. You MUST try the differnet cases including the one above and stop fooling and speculating about my issues!!!

2) "_If you want to create package from visual studio you can follow_"

I DON'T WANT to create a package from visual studio. What I really NEED is to create the one by script because it's all about the build automation process, isn't it???

By the way, visual studio USES msdeploy.exe in order to create web-packages EXACTLY as I described above.

3) I need to deploy ASP.NET CORE application so all your references above are absolutely useless because "WinRM - IIS Web App Deployment" task doesn't work for automatic asp.net core apllication deployment.

To sum it all up, "WinRM - IIS Web App Deployment" task MUST use the parameter "Website Name" and be able to deploy ANY package to IIS without any knowleadge about the PHYSICAL PATH of a site 
(for your convenience i even attached THE SCRIPT WITH A POSSIBLE SOLUTION!!!).

If the issue won't be fixed as soon as possible I will have to escalate the problem to your managers.

**Comment by mvvsubbu** [comment]
Asp.Net core apps we haven't tested and it is in our backlog. We will make sure your concern is addressed when we do that

**Comment by shamnigurat** [comment]
I'm really tired to explain you OBVIOUS things.
**It doesn't concern Asp.Net core apps DIRECTLY.**
It's all about how the "WinRM - IIS Web App Deployment" task deploys to IIS a web-package created with msdeploy.exe (it **doesn't matter** who and how created the web-package). **The task does it WRONG.**

**JUST TRY THE STEPS I'VE DESRIBED ABOVE!!!!!!! THERE IS  _OBVIOUS_  ERROR!!!!!!!!!!!**
And don't tell me I created my package wrong - it's the STANDARD WAY to create package with using msdeploy.exe.

Once more:
**"WinRM - IIS Web App Deployment" task MUST use the parameter "Website Name" and be able to deploy ANY package to IIS without any knowleadge about the PHYSICAL PATH of a site.**
For now **IT'S NOT POSSIBLE** and **MUST BE FIXED ASAP**.

**Comment by shamnigurat** [comment]
And remove "Invalid" label from the issue!!!!

**The issue is VALID.**

**Comment by KrishnaAdityaB** [comment]
@shamnigurat Thanks for the feedback and the fix.

I incorporated your fix and tested it. The existing CI/CD started breaking with the error "_Source (sitemanifest) and destination (iisApp) are not compatible for the given operation_". 
_Visual Studio Build_ task generates the web package with a manifest provider by default. And this package can't be deployed with _dest:iisApp_. 
As the primary use case we targeted first with this Extension is ASP.Net web apps built with _Visual Studio Build_ task, I can't take this fix as is right now.

I agree that the scenario you explained is valid. We will come up with a design to make it work for these two scenarios and can be extended to others later. I will change the title appropriately and mark this thread as enhancement.

And I agree with your feedback that the hint for _Website name_ field is not inline with the implementation. We will fix that.

**Comment by shamnigurat** [comment]
@KrishnaAdityaB Thanks a lot!!!

It's a ray of light in the darkness :)

**Comment by feco93** [comment]
Same issue here. "WinRM - IIS Web App Deployment" task fails.

**Comment by RoopeshNair** [comment]
@shamnigurat, 

Appreciate your feedback. I'm sorry for the issue you're experiencing. We will track the support for it in our backlog.

Current implementation of WinRM task has "-dest:auto" implicitly set and the package format needs "dest:iisApp" switch which is the issue..

For now, to unblock yourselves can you please try generating the package using below command using msdeploy:

"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:iisApp="O:\TestSite" -dest:package="WebApp.zip" -declareParam:name="IIS Web Application Name",defaultValue="WebApp",tags=IisApp,scope=IisApp,kind=ProviderPath -declareParam:name="IIS Web Application Name",scope=setAcl,kind=ProviderPath -replace:match="O:\TestSite",replace="WebApp" -verb:sync -retryAttempts:20 -disableRule:BackupRule

Let us know if the issue persists

**Comment by RoopeshNair** [comment]
@shamnigurat - I presume, you were able to unblock yourselves. One of the options we considered is to expose the "-dest" key as an additional parameter for the user to override. We will prioritize based on user feedback. Closing this for now. Please feel free to drop a note if you need more information. (roopesh dot nair at microsoft dot com)

Thank you!

**Comment by kieryn** [comment]
Any update on this?

**Comment by RoopeshNair** [comment]
@kieryn, can you please elaborate? are you looking for "-dest" key as an additional params? 

Thanks,

**Comment by kieryn** [comment]
@RoopeshNair -- No, the issue I was facing was that web deploy using MSBuild (from VS2017) to do web deploy to a Windows Server 2016 with IIS was failing with the website name not found error.  Even though, testing the web deploy publish connection was saying it was successful (The app I was trying to deploy is a .NET 4.5 web api app built in VS2015)   The website name was absolutely there - I was completely blocked to deploy so I am currently falling back on a Windows Server 2012 R2 instance instead.
