### ISSUE TITLE
logging in SqlPackage.exe

### ISSUE THREAD

**Issue by amccool** [Microsoft/vsts-rm-extensions#121]
using WinRM - SQL Server DB Deployment, how can I get the verbose logging output from sqlpackage.exe?

**Comment by mvvsubbu** [comment]
You can set system.debug variable to true for build / release definition. This will show the sqlpackage.exe logs

**Comment by mvvsubbu** [comment]
Any update?

**Comment by mvvsubbu** [comment]
I am considering you got what you are looking for and hence going ahead and closing the issue. Feel free to re-open if you didn't get what you are looking for.

**Comment by chucklu** [comment]
@mvvsubbu  Are you talking about [SqlPackage.exe](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver16)?
Could you give an example about how to pass system.debug varibale?

**Comment by mvvsubbu** [comment]
Currently I am not working in this team anymore. @kmkumaran can you add current owner for this task

**Comment by kmkumaran** [comment]
+ @rohit-batra and @vijayma

**Comment by chucklu** [comment]
@kmkumaran @mvvsubbu  Thanks for your effort, currently I can publish the .dac through latest version of vs2019.  Previously there is a bug in older vs2019 version, which make it impossible to publish database project through vs. After I upgrade vs 2019 to latest version, it works fine now. So, I won't need to publish .dac through command.
