### ISSUE TITLE
NET.TCP binding support

### ISSUE THREAD

**Issue by jfilburn** [Microsoft/vsts-rm-extensions#130]
Just wanted to ask if there is anything in the pipe for net.tcp binding support?

**Comment by KrishnaAdityaB** [comment]
@RoopeshNair ?

**Comment by RoopeshNair** [comment]
@jfilburn, we don't have this on our backlog. if we start getting multiple requests, we can re-evaluate and prioritize appropriately. 

Closing it for now.
Thank you
