### ISSUE TITLE
Having issues with credentials

### ISSUE THREAD

**Issue by kyurthich** [Microsoft/vsts-rm-extensions#133]
I seem to be getting stuck here, any ideas?

https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/Common/DeploymentSDK/Src/InvokeRemoteDeployment.ps1#L253

![image](https://cloud.githubusercontent.com/assets/3331097/19785155/60c9c73c-9c66-11e6-8847-c744a5e02b8c.png)

![image](https://cloud.githubusercontent.com/assets/3331097/19785169/7593c960-9c66-11e6-8527-6e30f939847f.png)

![image](https://cloud.githubusercontent.com/assets/3331097/19785234/ab9b26fc-9c66-11e6-8340-1525f2fb3032.png)

**Comment by kyurthich** [comment]
Ran into this. It seems like the password may be empty.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/2f8325b6-e633-423f-b6e7-cd9ba62ad740/vso-secret-variables-are-empty-at-build-time?forum=TFService

![image](https://cloud.githubusercontent.com/assets/3331097/19865940/aa76f34e-9f74-11e6-8535-e7042791ddb3.png)

**Comment by kyurthich** [comment]
Turns out, you have to unmask the field, fill in the value, then reset it to secret.
Otherwise the value will NOT save.

**Comment by KrishnaAdityaB** [comment]
@kyurthich 
Are you on TFS or VSTS?
If TFS - what is the TFS version? what is the Agent version?
If VSTS - are you still facing this issue? If yes, What is the Agent version? Can you provide us your VSTS account (https://<account>.visualstudio.com)?

**Comment by kyurthich** [comment]
I am VSTS. No longer an issue. On the VSTS side when you input a variable and mark it as a secret so it is not visible, Turns out to change it, first you have to unmark it as a secret, type in the new value, and remark it as a secret.
