### ISSUE TITLE
Sql DacPac deploy task doesnot log stderr to Build/Release log

### ISSUE THREAD

**Issue by KrishnaAdityaB** [Microsoft/vsts-rm-extensions#147]
Moving https://github.com/Microsoft/vsts-tasks/issues/3002 here

**Quoting issue**
When using the DacPac Deploy Task, I can see what looks like stdout in the build/release log. However, if the dacpac deployment fails, the stderr output does not appear in the build/release log. I do see:
```
Initializing deployment (Start)
Initializing deployment (Failed)

##[error]
ErrorRecord : *** Could not deploy package.

```
However, running the same command in a console gives the actual error (like incorrect SQL version or whatever). It would be great if the stderr was put onto the build/release logs so that we can see error details.

**Comment by KrishnaAdityaB** [comment]
This fix will be released soon. Until then there is a mitigation available.
You can add a Build/Release variable with name _System.Debug_ and value _true_. This will ouput verbose logs which contain the full error message

**Comment by KrishnaAdityaB** [comment]
Fix will be available in the next release. Meanwhile, please use the work around mentioned above.

**Comment by rloliveirajr** [comment]
Was this released already?

**Comment by KrishnaAdityaB** [comment]
@rloliveirajr yes, it was released. Are you still facing the issue? Can you provide your extension and task version?

@Ajay-MS can you share the extension release version containing this fix? I was not able to find the release branch.

**Comment by nickeyyan** [comment]
@KrishnaAdityaB do we need to update existed task?

**Comment by Ajay-MS** [comment]
This issue was fixed in extension version 1.3.0.

**Comment by nickeyyan** [comment]
After talk with Ajay-MS, as we meet this issue in VSTS-TASK not in extension. VSTS team still working on this issue. And it will be available on next 1-2 weeks.

**Comment by Ajay-MS** [comment]
With extension SQL server dacpac deployment task issue has been fixed with version 1.3.0.  This issue is with SQL Azure Dacpac deployment task that will be fixed soon.

**Comment by chshrikh** [comment]
fix will be available with next deployment

**Comment by nickeyyan** [comment]
when is the next deployment?

Thanks,
Nickey

________________________________
