### ISSUE TITLE
IIS Web App Deployment Using WinRM - why not webdeploy directly

### ISSUE THREAD

**Issue by larserikfinholt** [Microsoft/vsts-rm-extensions#153]
Hi!

As I understand, to use this task we need to first copy the zip to the target maching, then do a webdeploy. This involves opening ports for remoting 5986 and file copy 445. Why not use webdeploy directly? It would have been great to have a task that allowed my to pick a .zip (like the IIS Web App Deployment Using WinRM task) and then do a WebDeploy directly (only requires webdeploy port).

I tried the execute batch script, but it is a lot of arguments to put in, so having it as a task would be great.

Please let me know if I'm wrong on the need to to a filecopy first. Thanks

**Comment by RoopeshNair** [comment]
@larserikfinholt - webdeploy remote agent service is not installed by default. Also, we had a proven WinRM (PowerShell on Target) task. Which made sense to leverage WinRM option and run webdeploy locally, plus enable appcmd options as well. 

We encourage contributions, you can share one with webdeploy remote option, I'm sure many will benefit from it. 

Thank you

**Comment by AThomsen** [comment]
Any news on this enhancement?
It seems odd that a MS release system can't deploy to MS-web-servers using MS-deploy protocol (Webdeploy) directly.

**Comment by RoopeshNair** [comment]
@AThomsen, unfortunately no plans for this yet. If we have many requests (on user voice) we can reconsider

Thanks,

**Comment by twilly86** [comment]
Also looking for ability to do this
