### ISSUE TITLE
Override parameters not working after 1.4.0 update

### ISSUE THREAD

**Issue by rodrigoff** [Microsoft/vsts-rm-extensions#161]
Since the update to 1.4.0 version today, the field "Override parameters" is not working as expected. 
The parameters there are being ignored and the values defined in the parameters file is being used instead.

I've rolled back to 1.3.0 and this issues doesn't happen.

Was there any change in the parameter override structure in this update?

**Comment by alondero** [comment]
Our release pipeline has broken today because of this issue :-(

**Comment by Kitcheone** [comment]
Yep, we're having the same issue with 1.4.0

**Comment by marcodiniz** [comment]
We are also unable to deploy because this

**Comment by ksix** [comment]
Yeah this has killed us as well. How can we roll back to version 1.3?

**Comment by Ajay-MS** [comment]
I apologize for issue, I have created PR for fixing this issue. Will update extension soon.

**Comment by Ajay-MS** [comment]
Task has been updated with fix for above mentioned issue. Can you please confirm if you are still facing any issue with task.

**Comment by alondero** [comment]
@Ajay-MS yes can confirm this is fixed now. Feel free to reject my PR I raised for this yesterday

**Comment by Ajay-MS** [comment]
@alondero 
Thanks for confirming same and thanks for raising a PR too 👍

**Comment by rodrigoff** [comment]
@Ajay-MS 
Confirmed it's fixed. Thanks 👍

**Comment by Ajay-MS** [comment]
@rodrigoff 
Thanks for confirmation. Closing this issue feel free to open if you ever face any problem again.
