### ISSUE TITLE
Approach to Deploy an App to Servers Hosted in Azure

### ISSUE THREAD

**Issue by brett3210** [Microsoft/vsts-rm-extensions#167]
The following page uses the "IIS Web App Deployment Using WinRM" task:
https://www.visualstudio.com/en-us/docs/release/examples/other-servers/net-to-vm

However, it states:
"To deploy an app to servers hosted in Azure, see Deploy ASP.NET apps to Azure virtual machines."
https://www.visualstudio.com/en-us/docs/release/examples/azure/net-to-azure-vm
That is, use the Run Powershell Task instead to deploy.

Is there a particular reason why the "IIS Web App Deployment Using WinRM" Task shouldn't be used in the "deploy an app to servers hosted in Azure" scenario?

**Comment by chshrikh** [comment]
"IIS Web App Deployment Using WinRM" can be used to deploy a web site on any vm 
( local network vm or azure vms) / physical machines.
If you want to any generic deployment other than web site deployment, you can write your own powershell deployment script and use the Powershell On Target Machine task against all machines.

**Comment by brett3210** [comment]
Thanks, it may be worth updating the web page to make it clear that "IIS Web App Deployment Using WinRM" can equally be used for the "deploy an app to servers hosted in Azure" scenario

**Comment by mvvsubbu** [comment]
Thanks for confirmation. We have updated readme that is common for all WinRM tasks under notes section https://github.com/Microsoft/vsts-rm-extensions/blob/master/Extensions/IISWebAppDeploy/Src/README.md
