### ISSUE TITLE
Extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by philcart** [Microsoft/vsts-rm-extensions#168]
Running TFS 2015 Update 3  (14.102.25423.0 (Tfs2015.Update3))
When I try to install the extension it fails with the following. The full log file is attached

`21/12/2016 4:54:26 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.`
`    at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)`
`    at VSIXInstaller.App.InitializeInstall()`
`    at System.Threading.Tasks.Task.InnerInvoke()`
`    at System.Threading.Tasks.Task.Execute()`

[VSIXInstaller_017e5280-1c57-482e-af84-dc2ad970da77.txt](https://github.com/Microsoft/vsts-rm-extensions/files/665573/VSIXInstaller_017e5280-1c57-482e-af84-dc2ad970da77.txt)

**Comment by philcart** [comment]
Previous log file was from Desktop attempt. This log file is from the TFS Server itself

[VSIXInstaller_651909a5-7c46-4d3e-9833-a077d24195e5.txt](https://github.com/Microsoft/vsts-rm-extensions/files/665581/VSIXInstaller_651909a5-7c46-4d3e-9833-a077d24195e5.txt)

**Comment by chshrikh** [comment]
Can you please specify how you are trying to install it ? Could you please refer this https://www.visualstudio.com/en-us/docs/marketplace/get-tfs-extensions

**Comment by chshrikh** [comment]
you may refer this as well https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/31/team-foundation-server-extensions-2/

**Comment by philcart** [comment]
Was able to install this extension via the upload method described in the blog post.

For others that may be struggling with this.
1. Find the extension in Marketplace
2. Download vsix file
3. Open on-premises TFS Web site
4. Navigate to the Local Gallery to Manage Extensions
5. Upload vsix file downloaded in step 2
6. Install extension to collection(s)

Hmmm ... now I wonder why it's not that intuitive and straigtforward?

Cheers
Phil
