### ISSUE TITLE
Cant deploy simple website package to default website, WINRM IIS DEPLOY TASK SITE DOES NOT EXISTS

### ISSUE THREAD

**Issue by amarpandharpure** [Microsoft/vsts-rm-extensions#172]
i want to simply deploy my web package to Default Web Site.

Does the website name param is correct way to do this.

I tested app mgmt task it works fine so no env issue. I also tried with additional argument in msdeploy 
-setParam:kind=ProviderPath,scope=contentPath,value=$(WebSiteName)

Any urgent help ??

**Comment by mvvsubbu** [comment]
Sorry for the late reply. Are you still blocked, if yes can share full logs by system.debug variable to true

**Comment by mvvsubbu** [comment]
I am closing issue as i didn't hear back. If still having any problem please share logs
