### ISSUE TITLE
Setparameters.xml file

### ISSUE THREAD

**Issue by eliassal** [Microsoft/vsts-rm-extensions#183]
Very useful tool. It works like a charm with my onPremise TFS.
Can you please provide a template or an expample fro setparameters.xml file or a url describing what and how we can use this file?
Thanks in advance

**Comment by mvvsubbu** [comment]
Refer https://msdn.microsoft.com/en-us/library/dd465323(v=vs.110).aspx. If you need any further assistance you can mail to RM_Customer_Queries at Microsoft dot com
