### ISSUE TITLE
WinRM - IIS Web App Management - Add multiple bindings

### ISSUE THREAD

**Issue by gandarez** [Microsoft/vsts-rm-extensions#188]
is there a way of adding multiple bindings? Should I use AppCmd including additional arguments?

![image](https://cloud.githubusercontent.com/assets/782854/22509134/dab7020e-e873-11e6-8340-3607a5794ea6.png)

**Comment by nathan-alden-hp** [comment]
@gandarez I have the exact same question. How did you end up solving this? I'm also thinking of using AppCmd.exe commands.

**Comment by gandarez** [comment]
To setup multiple binds you must pass additional AppCmd.exe commands

`Advanced > Additional AppCmd.exe Commands`

```
set app "MyWebSite/" /enabledProtocols:http,net.tcp
set site /site.name:MyWebSite /+bindings.[protocol='http',bindingInformation='*:SOME-PORT-FOR-WEBSITE:'] | set errorlevel=0
set site /site.name:MyWebSite /+bindings.[protocol='net.tcp',bindingInformation='808:SOME-ALIAS'] | set errorlevel=0```
