### ISSUE TITLE
Physical Path removing \

### ISSUE THREAD

**Issue by renatotkr** [Microsoft/vsts-rm-extensions#193]
I'm using the latest version 1.4.3, and it appears to be trimming the slashes on the physical path when creating a web site

I'm trying to point to a network share, but it deploys without the \\

eg
\\fabrikam\site\
on IIS
fabrikam\site

**Comment by mvvsubbu** [comment]
https://github.com/Microsoft/vsts-rm-extensions/pull/194 Fix checked in will be released along with other issues. Closing the issue
