### ISSUE TITLE
Win-RM SQL Server DB Deployment DACPAC doesn't log command output

### ISSUE THREAD

**Issue by manicprogrammer** [Microsoft/vsts-rm-extensions#197]
I have seen the comment about the error messages not logging and to turn on system.debug and set to true in the variables which I have done but for a successful deploy I expected to see all text I see when I run it manually from the command line instead of that detailed output all I get is something like below after the debug variable information is printed for the task.

Is this by design that all the output from the sqlpackage.exe command is lost or is there a means to collect that output into the release management deployment logs that I am missing?

```
Entering script SqlPackageOnTargetMachines.ps1
 
Sql Versions installed on machine ******** as read from registry: 110 100 90
 
Sql Version Specific Root Dir for version 110 as read from registry: C:\Program Files\Microsoft SQL Server\110\
 
Sql Version Specific Root Dir for version 110 as read from registry: C:\Program Files (x86)\Microsoft SQL Server\110\
 
Dac Framework installed with SQL Version 110 found at C:\Program Files (x86)\Microsoft SQL Server\110\Dac\bin\SqlPackage.exe on machine ******
 
Dac Framework installed with SQL Version 120 found at C:\Program Files\Microsoft SQL Server\120\DAC\bin\SqlPackage.exe on machine ******
Visual Studio versions found on machine ******* as read from registry: 14.0 12.0 11.0 10.0 9.0 8.0
 
Visual Studio install location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
 
Dac Framework installed with Visual Studio found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe on machine *******
 
File is D:\DBDeployment\DBProject.dacpac
 
Sqlpackage.exe arguments :  /SourceFile:"D:\DBDeployment\DBProject.dacpac" /Action:Publish /Profile:"D:\DBDeployment\*****.xml" /q:false 
/SourceFile:"D:\DBDeployment\DBProject.dacpac" /Action:Publish /Profile:"D:\DBDeployment\*****.xml" /q:false
 
Executing command: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe  /SourceFile:"D:\DBDeployment\DBProject.dacpac" /Action:Publish /Profile:"D:\DBDeployment\*******.xml" /q:false
 
 Successfully deployed using dacpac
```

**Comment by niadak** [comment]
@manicprogrammer Thanks for reporting the issue. We will fix the bug and update here.

**Comment by Ajay-MS** [comment]
@manicprogrammer 
Closing this as issue has been resolved. Please feel free to reopen if you still facing this issue.

**Comment by hrboyceiii** [comment]
@Ajay-MS what was the resolution to this? I'm not seeing a commit to reference the changes that enables output during task execution.  I ask because to workaround while using older versions, I manually updated and set $VerbosePreference = "Continue".  I want to know the version so I have reason to ask a customer to update this extension on their on-prem TFS2017.

Thanks
