### ISSUE TITLE
Unable to deploy DACPAC file using utility Deploy using: DACPAC

### ISSUE THREAD

**Issue by RupaliGarg09** [Microsoft/vsts-rm-extensions#201]
![2017-02-22 19_02_10-inbox - rupalig maqsoftware com - outlook](https://cloud.githubusercontent.com/assets/25955858/23213604/8c51b11c-f931-11e6-9502-96f739f3e716.png)

**Comment by arjgupta** [comment]
Hi @RupaliGarg09 , can you send the complete debug log for the task to RM_Customer_Queries@microsoft.com. You can generate the debug logs by setting the system.debug variable to true in the variables tab

**Comment by niadak** [comment]
Hi @RupaliGarg09 , I am closing the issue as we have resolved your issue offline. The issue was with WinRM configuration on the target machine. Please feel free to reopen if you are still block on this
