### ISSUE TITLE
Verbose output

### ISSUE THREAD

**Issue by marioleed** [Microsoft/vsts-rm-extensions#202]
Is there a way to enable more verbose output in the VSTS logs for deployments? It seems pretty sparse as of now and it would be great to see the commands that are actually executed (e.g. msdeploy.exe commands).

This is a question and/or an enhancement.

**Comment by jabbera** [comment]
More then setting system.debug=true in the variables screen?

**Comment by marioleed** [comment]
@jabbera, Yep, that didi it! Can I suggest adding that to the docs?

Thank you for helping and the quick reply!
