### ISSUE TITLE
IISWebAppDeploy: override parameters must not contain spaces between `name` and `value`

### ISSUE THREAD

**Issue by mderriey** [Microsoft/vsts-rm-extensions#203]
Hi,

I started using the IIS Web app deployment task. As I keep the Web Deploy parameters in the release definition, I don't have a parameters file, so I used the override parameters feature.

It's very handy, but it should be more explicit that there must be absolutely no space between the comma after the `name` token and the `value` token.

Meaning, it cannot be `name="<parameterName>", value="<parameterValue>"`, but instead must be `name="<parameterName>",value="<parameterValue>"`. Note the space between the comma and the `value` token.

It doesn't help that in the help text, the second example - the one supposed to be on the second line - includes such a space.

The error I got was `System.Exception: Error: Unrecognized argument 'value="<value of the parameter of the line that contained a space>"'. All arguments must begin with "-".`.

After removing the spaces, it's all good!
Thanks for the hard work. I'll send a PR related to this issue to fix the help text.
Feel free to contribute to the PR branch to add anything you think might be worth it.

**Comment by niadak** [comment]
@mderriey Thanks for pointing out the issue. We will fix the issue and handle the space.

**Comment by mderriey** [comment]
Closing as the associated issue was closed. See https://github.com/Microsoft/vsts-rm-extensions/pull/204#issuecomment-287677410

It was fixed in #205.
