### ISSUE TITLE
Deploy IIS App - Documentation Bug

### ISSUE THREAD

**Issue by karlrissland** [Microsoft/vsts-rm-extensions#206]
The documentation referencing the format for override parameters is incorrect, as is the tooltip for the task.  The documentation and tooltip reference the following format;
For example, name="IIS Web Application Name",value="Fabrikam/MyApplication"

This generates the following error;
2017-03-15T12:04:02.8906659Z Deployment failed on machine NBWin with following message : System.Exception: Error: Unrecognized argument 'value="Data Source=NBSql;Initial Catalog=PeopleDB;Integrated Security=False;User Id=*****;Password=****;MultipleActiveResultSets=True"'. All arguments must begin with "-".

The correct format for the override parameters is actually; 
"PeopleDb-Web.config Connection String"="Data Source=NBSql;Initial Catalog=PeopleDB;Integrated Security=False;User Id=****;Password=****;MultipleActiveResultSets=True"

Task works fine once you figure out the right format for the override params.

**Comment by niadak** [comment]
@karlrissland  Thanks for reporting the issue. This is a known bug
**override parameters must not contain spaces between `name` and `value`** as reported in the issue **https://github.com/Microsoft/vsts-rm-extensions/issues/203**. We will fix the issue ASSP. Please remove the pace between the comma after the name token and the value token as a workaround for now.

**Comment by niadak** [comment]
Fixed the tool tip and removed the space
