### ISSUE TITLE
Cannot install on TFS

### ISSUE THREAD

**Issue by varnk** [Microsoft/vsts-rm-extensions#208]
Downloaded the extension and then tried to upload to TFS 2015  extension manager.  I get the following error:

Unable to publish extension due to:
Missing contribution (ms.vss-releaseartifact.artifact-types)

**Comment by mvvsubbu** [comment]
Can you specify which extension you have tried uploading?

**Comment by omeshp** [comment]
Artifact extensions aren't supported for TFS 2015 update 3, It is only supported TFS "15" RC onwards.
