### ISSUE TITLE
variable inside variables has not been replace

### ISSUE THREAD

**Issue by jmvtrinidad** [Microsoft/vsts-rm-extensions#211]
As title said, i created variable 

- path - $(build.artifactstagingdirectory)\for-deploy\website

but the output is `C:\agent\_work\r1\a\$(build.artifactstagingdirectory)\for-deploy\website`. It seems the variable `build.artifactstagingdirectory` has not been replace.

**Comment by niadak** [comment]
@jmvtrinidad , This issue has been fixed. Please feel free to reopen the issue if you are still facing the issue
