### ISSUE TITLE
First line of "Override Parameters" for SetParameters Fails to Be Sent to MSBuild

### ISSUE THREAD

**Issue by corsairmarks** [Microsoft/vsts-rm-extensions#214]
If I submit multiple lines of Override Parameters, the first line seems to not be sent to MSBuild.

```
name="Param1",value="val1"
name="Param2",value="val2"
```

MSBuild only receives Param2 in this case.  I seem to be using version 1.4.3 through VSTS.  If possible, I'd like to upgrade to the latest version but I don't see how that is possible in VSTS.

**Comment by niadak** [comment]
Sorry for delayed response.
Can you please raise a issue in https://github.com/Microsoft/vsts-tasks/issues if you are still facing this issue? MSBuild task team should help here.

**Comment by corsairmarks** [comment]
I'll add an issue if I encounter it again.  I'm no longer on contract for the project when I experienced the issue.
