### ISSUE TITLE
`Build.BuildNumber` doesn't work for deploying TeamCity builds

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-rm-extensions#216]
If I create a release definition using a TeamCity build as artifact source, and `$(Build.BuildNumber)` as Release name format, releases are still named using the default naming schema (`Release-1`, ...)

**Comment by omeshp** [comment]
@pascalberger This issue is fixed in latest vsts release, can you confirm that it is working for you now?

**Comment by pascalberger** [comment]
@omeshp We're using TFS on-prem (currently 2018 RTM). If you let me know in which TFS version this is supposed to be included I can test as soon as it is released.

**Comment by omeshp** [comment]
@pascalberger Hi pascal, this fix will get released with TFS 2018 update 2.
