### ISSUE TITLE
IISWebAppDeploy : XML transformation issue

### ISSUE THREAD

**Issue by marco-gallinari** [Microsoft/vsts-rm-extensions#274]
Hi, 
using IISWebAppDeploy task on VSO, everything works fine but applying XML transformation per environment the transformed XML is not indented, and this generates issues with configuration parser, as in this bug report:

https://blogs.msdn.microsoft.com/tess/2010/02/16/system-configuration-configurationerrosexception-unrecognized-element-setting-and-other-unrecognized-elements/ 

eg., this happens in applicationSettings section, with multiple assembly  "setting" tags:

```
<My.Properties.Settings>
    <setting name="SettingA" serializeAs="String">
      <value>ValueA</value>
    </setting>
    <setting name="SettingB" serializeAs="String">
      <value>ValueB</value>
    </setting>
</My.Properties.Settings>
```

When transformed with the task, it becomes:

```
<My.Properties.Settings>
    <setting name="SettingA" serializeAs="String"><value>TransformedValueA</value></setting><setting name="SettingB" serializeAs="String"><value>TransformedValueB</value></setting>
</My.Properties.Settings>
```

which won't be parsed correctly.

**Comment by vincentdass** [comment]
@marco-gallinari , this issue is related to [VSTS-TASKS ](github.com/Microsoft/vsts-tasks).
Closing this issue.

**Comment by vincentdass** [comment]
Created a fix for the same [here](https://github.com/Microsoft/vsts-tasks/pull/5312).
