### ISSUE TITLE
"External TFS" Service endpoint type not available on my OnPremises installation

### ISSUE THREAD

**Issue by ruairiohagan** [Microsoft/vsts-rm-extensions#280]
Hi, 

I can't set up a connection to my remote TFS installation as I can't add a service endpoint of the above type.

The extension is installed on an on-premises TFS server, trying to deploy builds from the development environment into the production environment.

I'm running TFS 2017.2 on both servers.

Help?

Thanks.

**Comment by GitHubSriramB** [comment]
@ruairiohagan - This endpoint type is there as part of the following extension:
https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-externaltfs
 
With TFS 2018, we moved this endpoint type into TFS itself.

But until you move to TFS 2018, you would need to install the extension in TFS to get this endpoint type.

Hope this helps.

**Comment by ruairiohagan** [comment]
Hi @GitHubSriramB,

I have that extension installed on my local TFS 2017.2 installation.

But when I go to the configure Services tab and click "New Service Endpoint", "External TFS" just isn't there.

I've tried it on three different local TFS instances (all that version), I can't get the endpoint type to appear on any of them.

Are there any other prerequisites I need to install that I may be missing?

**Comment by GitHubSriramB** [comment]
@ruairiohagan - Apologies for the confusion.

We have actually moved the endpoint type into TFS with TFS 2017 Update2 itself. 

The endpoint type will appear with display name "Team Foundation Server/Team Services".

Could you check if you are able to view this endpoint type & work with it?

**Comment by ruairiohagan** [comment]
hi @GitHubSriramB ,

That was it, it's working now, thanks!

I had tried that endpoint type previously, but before I had installed the External TFS extension, I just didn't retry after I installed because I was expecting the "External TFS" to be there!

Thanks again for your help.

Ruairi.
