### ISSUE TITLE
IIS Web App Deploy - XML variable substitution - removes XML declaration

### ISSUE THREAD

**Issue by NickMRamirez** [Microsoft/vsts-rm-extensions#290]
The XML declaration at the top of a web.config file, e.g.:

```
<?xml version="1.0" encoding="UTF-8"?>
```

seems to be removed from the file when the *XML variable substitution* checkbox is checked on the *IIS Web App Deploy* task. This is not critical because the declaration is optional for `version="1.0"`.

**Comment by niadak** [comment]
@NickMRamirez , Can you please open a issue in https://github.com/Microsoft/vsts-tasks/issues as the relevant task in that repo.

Can you share the web.config file with us. Is "<?xml version="1.0" encoding="UTF-8"?>" the first line in the file or you have any comments at first? 

Please keep the line at top of the file and try once.

**Comment by niadak** [comment]
@NickMRamirez Any update on this? Is "<?xml version="1.0" encoding="UTF-8"?>" the first line in the file or you have any comments at first? Can you please make sure  "<?xml version="1.0" encoding="UTF-8"?>" is the first line and try once?

**Comment by NickMRamirez** [comment]
@niadak In retrospect, it isn't an important problem, since the XML declaration is optional. I'd probably just close this issue.
