### ISSUE TITLE
Feature request: Download Artifacts External TFS Git (plugin) 

### ISSUE THREAD

**Issue by ParidaPunyasloka** [Microsoft/vsts-rm-extensions#315]
Hello,

This is a great plugin and I have implemented this in a number of build definitions and has been helpful in keeping external dependent code in a sperate repo and use them during the build. I just want to request, in the Commit Id option of this task, can we have the o[ption to select "latest" as in to pick up the latest commit instead of choosing the commit id. 

Use case: In case, I update my external repo, I have to edit the build definition and select the latest commit id but if I could get a feature to set it to latest, I don't have to edit my build definition every time I update my external repo. 

Thanks

**Comment by GitHubSriramB** [comment]
@ParidaPunyasloka - Thanks for the feedback. We will add this request to our backlog.
