### ISSUE TITLE
WebDeploy error with tokens replaced by XML strings in SetParameters.xml file on VSTS

### ISSUE THREAD

**Issue by Philippe85** [Microsoft/vsts-rm-extensions#339]
On VSTS, I use the "Replace Tokens" task to replace tokens in SetParameters.xml file with VSTS variables. But I have variables which contains a XML string.

For example, with a VSTS variable which contains:
`<string>aaa</string><string>bbb</string><string>ccc</string>`
I got in the SetParameters.xml:
`<setParameter name="FolderTreeStructureRootFullControl"
               value="<string>aaa</string><string>bbb</string><string>ccc</string>" />`

After, when I deploy the website with the "WinRM - IIS Web App Deployment" task in a VSTS Release Definition, I have this error :
`System.Exception: Error: '<', hexadecimal value 0x3C, is an invalid attribute character.`

Is there a way to fix this error without replace all '<' and '>' characters by &lt; and &gt; escape strings, to keep variable contents readable ?

Thank you.

**Comment by rajatagrawal-dev** [comment]
You will have to escape the the < symbol atleast. > might not need to be escaped. But your original concern of readable variables will not be addressed by this either.
Please read [this](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/1091953#1091953) for reference on XML character escaping.
