### ISSUE TITLE
Timeout occurs during Download Artifact step of Release Definition using TeamCity Artifacts for Release Management extension, causing release to fail. 

### ISSUE THREAD

**Issue by connorposke** [Microsoft/vsts-rm-extensions#383]
When using the TeamCity Artifacts for Release Management extension, the “Download Artifacts” step times out after about 20 seconds. This is the step where VSTS attempts to download specific artifacts from TeamCity. The connection between the TeamCity server and VSTS is confirmed to be successfully established: The Service Hook successfully verifies the connection on demand. We are also able to witness in the TeamCity server logs that the REST API Request to pull the artifacts is successfully coming through from VSTS. Based on the observed behavior and characterization of the issue, it seems to appear that the TeamCity VSTS extension is simply timing out too soon for no reason. The artifacts being requested are large in size (150Mb). The connection between VSTS and TeamCity appears to be slow, based on how long it takes VSTS forms to populate with metadata pulled from TeamCity such as artifact names and versions. The TeamCity instance is hosted in an Azure VM.  Release Logs with timeout error attached. 
[ReleaseLogs_48.zip](https://github.com/Microsoft/vsts-rm-extensions/files/1697114/ReleaseLogs_48.zip)

**Comment by omeshp** [comment]
Looks like we don't set any timeout for custom artifacts at https://github.com/Microsoft/vsts-agent/blob/f7d9051f92cfdc1d55982483f09cc5531f7dd55e/src/Agent.Worker/Release/Artifacts/CustomArtifact.cs which needs to be fixed.

**Comment by omeshp** [comment]
@connorposke We have recently shifted from zip based download to file based download for teamcity extension, so this issue should be resolved now. Can you confirm?

**Comment by omeshp** [comment]
Closing since there was no reply.

@connorposke Please reopen if you are still facing this issue.
