### ISSUE TITLE
Additional requirements make management more difficult

### ISSUE THREAD

**Issue by chriswgr** [Microsoft/vsts-rm-extensions#400]
Why are the default requirements for this task more stringent than the MSDeploy command line parameters?  If this task is intended to be a wrapper for MSDeploy -verb:sync, then you only additional parameters for package location (-source:package=<location>) and -dest:auto.

These are not requirements to run MSDeploy from a command line:
- Machines
- Admin Login
- Password
- Website Name
- Remove Additional Files at Destination

By enforcing unnecessary requirements, this task is going to cause my team more management overhead.  
1. We keep the website name in a SetParameters.xml file.  So for this piece of data, our configuration management has doubled.
2. Our agent runs on a domain-joined machine and MSDeploy works perfectly well in this type of environment. But this task forces us to manage credentials.

**Comment by RoopeshNair** [comment]
Check out [deployment-groups](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/) and [end-to-end CI/CD configuration for IIS web app deploy](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/deploy-webdeploy-iis-deploygroups?view=vsts&_lrsc=af2774f2-706a-4d11-810e-de23b8270485) support in deployment groups (DG). With DG, you don't need additional information viz. machine details, credentials etc. Also, the task is richer than WinRM based IIS deploy task. 

Another option is to explore msdeploy tasks from marketplace
