### ISSUE TITLE
How to set default artifact version when downloading from TFS

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-rm-extensions#401]
When you want to download an artifact from an External TFS, you don't get the same options to choose a default version or branch.

The lack of this feature really limits the usefulness of this extension in my case.  

- Is this feature on the backlog?
- is there anything specific blocking this feature?

**Comment by omeshp** [comment]
@GitHubSriramB Can you confirm if we have this on backlog?
@gregpakes btw adding default version for artifacts is extensible the documentation is at https://github.com/Microsoft/vsts-rm-extensions/blob/master/docs/authoring/artifactextension.md if you want to have a stab at it.

**Comment by GitHubSriramB** [comment]
@gregpakes - we will add this to our backlog. Thanks for the feedback.
