### ISSUE TITLE
Example of "Web Deploy Parameters File"?

### ISSUE THREAD

**Issue by RubixRevenge** [Microsoft/vsts-rm-extensions#405]
Can you provide an example of "Web Deploy Parameters File" in use, say to do a web.config transform to a specified configuration or otherwise ensure that the web.config has the correct values for a target environment (e.g., if the target environment is "production" then the correct connection strings are in the web.config file).

This is all I see under the topic. It does not provide sufficient explanation to use this field, as I am doing this for the first time.

> "Web Deploy Parameters File: The parameter file is used to override the default settings in the web deploy zip package file like, the IIS Web application name or the database connection string. This helps in having a single package that can be deployed across dev, test, staging, and production, with a specific parameter file for each environment. The parameter takes in the location of the parameter file on the target machines or on a UNC path."

**Comment by Ajay-MS** [comment]
@RubixRevenge 
Explaining with an example:

**Web.config**
Suppose your web app package contains config file in the following format
```
 <connectionStrings>
    <add name="DefaultConnection" connectionString="<connection string1>"
      providerName="System.Data.SqlClient" />
 </connectionStrings>
```

**Declarative paramters.xml**
And web app package already contains a parameters.xml file ( this file is generally termed as declarative paramters.xml file). The connection string in web.config file will be replaced by connection string from this file during execution of web deploy task 
```
<parameters>
	  <parameter name="DefaultConnection" defaultValue="<connection string2>" >
	  </parameter>
</parameters>
```
**Set Parameters.xml**
Now _Web Deploy Parameters File_ that you mentioned and it will have preference on above two. This file is generally termed as set parameters file.
```
<?xml version="1.0" encoding="utf-8"?>
	<parameters>
	  <setParameter name="DefaultConnection" value="<connection string 3>" />
</parameters>
```

If you have all three files connection string will be `<connection string 3>`.

Let me know if you have any other doubt on this.

**Comment by RubixRevenge** [comment]
Thanks. That example helps. What about a scenario where you have multiple connections strings in web.config that are all to be used in production. You need one set of strings for your dev environment, a separate set of strings for your demo environment, and a third set of strings for the production environment.

Would "Web Deploy Parameters" be the correct tool to determine which set of connection strings need to be in the released web.config?

To give you more context, I'm using TFS 2018 to release to IIS. The Visual Studio Build step packages the built package into a zip file, and so far I don't see any obvious means in WinRM to indicate "use this web.[name].config transform" or use "[name]" configuration. 

In my dev environment, my connection strings look like:
```
<connectionStrings>
    <add name="PermissionsOfRolesContext" connectionString="data source=HENRYW-PC\CARDIFF;" [the rest is redacted] />
    <add name="AltEdCertificationContext" connectionString="data source=HENRYW-PC\CARDIFF;" [the rest is redacted] />
  </connectionStrings>
```

In the demo environment, I would need the web.config connection strings to look like this:
```
<connectionStrings>
    <add name="PermissionsOfRolesContext" connectionString="data source=rmg-sand;" [the rest is redacted] />
    <add name="AltEdCertificationContext" connectionString="data source=rmg-sand;" [the rest is redacted] />
  </connectionStrings>
```

In the production environment, I would need the web.config connection strings to look like this:
```
<connectionStrings>
    <add name="PermissionsOfRolesContext" connectionString="data source=london;" [the rest is redacted] />
    <add name="AltEdCertificationContext" connectionString="data source=london;" [the rest is redacted] />
  </connectionStrings>
```

Am I on the right track by considering Web Deploy Parameters or do I need to look at another component in WinRM? Or is what I'm trying to do not supported by WinRM at all.

**Comment by Ajay-MS** [comment]
You can achieve substitution of values across multiple connection strings using XML variable substitution. 

[Variable substiution and transformation](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution?view=vsts) 

But this feature is not supported for WinRM based web app deploy task. 

I would suggest you here to [configure deployment group]( https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/?view=vsts) and use "IIS Web App Deploy" task which supports variable substitution. 

Let me know if you face any issue for configuration of deployment group.

**Comment by RubixRevenge** [comment]
Thank you. This statement says it all:  "But this feature is not supported
for WinRM based web app deploy task."


I was hoping that WinRM would have an option that makes my life easier. At
present, I do have another method that does work correctly, but there are
more steps involved.

Henry Wyckoff
henry.wyckoff@gmail.com

**Comment by milendimo** [comment]
For future references, by the looks of it "IIS Web App Deploy" is deprecated in TFS 2018. WinRM task does offer similar properties, e.g. Web Deploy Parameter File and Override Parameters, which are passed down the line to the web deploy executable. 
In case you are having trouble with the format of the file, I can highly recommend using the following VS extension:  [(Web Deploy Parameters Toolkit)](http://vsixgallery.com/extension/6435437e-72fb-4626-9a47-865f185ce258/)
