### ISSUE TITLE
Add other MSDeploy arguments

### ISSUE THREAD

**Issue by joecoolish** [Microsoft/vsts-rm-extensions#41]
Reading through the MsDeployOnTargetMachines.ps1 code, I see that all of the Override Parameters are forced into the "-setParam:" flag for the MSDeploy command.

I have a requirement for one of my deployments to add a `-skip:Directory=\\LoadedAssemblies` to the MSDeploy, and I was able to do this by modifying the `Get-MsDeployCmdArgs` function in MsDeployOnTargetMachines.ps1 to include the following code:

```
foreach($setParam in $setParams)
    {
        $setParam = $setParam.Trim()
        if(-not [string]::IsNullOrWhiteSpace($setParam))
        {
            if($setParam.StartsWith("-")) 
            {
                $msDeployCmdArgs = [string]::Format('{0} {1}', $msDeployCmdArgs, $setParam)
                continue
            }
            $msDeployCmdArgs = [string]::Format('{0} -setParam:{1}', $msDeployCmdArgs, $setParam)
        }
    }
```

Obviously, this isn't the most optimal solution, but it allowed me to add the custom flag into the command and deploy my web application.

Are there any plans to add the functionality to add custom MSDeploy flags in natively?  Maybe as a separate input in the Advanced section of the Task?

**Comment by mvvsubbu** [comment]
Yes there are plans to add additional commands as well as skip target directory and few other. Currently we are working on enabling Sql Task once that is done we will work on this.

**Comment by joecoolish** [comment]
Sweet!  I can't wait!  Until then, I'll use the patch above.  Great work!

**Comment by mvvsubbu** [comment]
You could float a PR by adding additional arguments input for task, we are open for contributions :)

**Comment by mvvsubbu** [comment]
These features are deployed with 1.2.0 version
