### ISSUE TITLE
Tests fail on Unix (Linux and Mac OS X)

### ISSUE THREAD

**Issue by pdesgarets** [Microsoft/vsts-rm-extensions#412]
Hi,
Tests fail UNIX systems, see https://travis-ci.org/pdesgarets/vsts-rm-extensions/builds/364061762 
Thanks

**Comment by omeshp** [comment]
#417

**Comment by omeshp** [comment]
@pdesgarets The issue is fixed now.

**Comment by pdesgarets** [comment]
Thanks ! Do you know when it will be released on VSTS public website ? It may solve https://developercommunity.visualstudio.com/content/problem/230303/artifacts-selection-for-release-works-only-on-wind.html .

**Comment by omeshp** [comment]
@pdesgarets yes to fix that issue we need some server side change also, which should be deployed in 3-4 days.

**Comment by pdesgarets** [comment]
Great, thanks
