### ISSUE TITLE
Application Pool (Create or Update) with "No Managed Code" results in AppCmd 80070057

### ISSUE THREAD

**Issue by dzimmyman** [Microsoft/vsts-rm-extensions#43]
Setting .NET Version to the item "No Managed Code" produces appcmd error 80070057.  Viewing the actual command that gets run, you can see that the selection actually gets passed as /[name='"MyAppPoolName"'].managedRuntimeVersion:**No Managed Code**
 instead of just a blank.  

The work-around is to choose one of the other options (e.g. v4.0) and pass in an **Additional AppCmd.exe Commands** without any value, for example  
set config /section:applicationPools /[name='MyAppPoolName'].managedRuntimeVersion:

Sorry, no time to fix and submit a pull request.  Hope this helps, though.

**Comment by dzimmyman** [comment]
Reconfirming suspiscion, running the deploy with **system.debu** shows the following command is run (abbreviated) and the parameter for  : "C:\Windows\system32\inetsrv\appcmd.exe"  section:system.applicationHost/applicationPools /[name='"CrmWebApiTest"'].managedRuntimeVersion:No Managed Code .... etc   
Sorry, no time to fix and submit pull request.

**Comment by mvvsubbu** [comment]
Issue is addressed it will be available in next release

**Comment by dzimmyman** [comment]
Thanks, I tried the latest and it now works as expected.
