### ISSUE TITLE
Update endpoint documentation to clarify how URL can be defined inline within data source binding 

### ISSUE THREAD

**Issue by GitHubSriramB** [Microsoft/vsts-rm-extensions#430]
Refer to the following customer issue:
https://github.com/Microsoft/vsts-tasks/issues/7302

We currently don't include this documentation here:
https://github.com/Microsoft/vsts-rm-extensions/blob/master/docs/authoring/endpoints/dataSources.md

**Comment by omeshp** [comment]
Documentation is updated
