### ISSUE TITLE
Admin login and password

### ISSUE THREAD

**Issue by scgbear** [Microsoft/vsts-rm-extensions#44]
Would it be possible to remove the admin login and password from the configuration. Perhaps have the option to have it run within the context of the build agents credentials? 

I'm working with an organization that will not be able to use the IIS Web Deploy and Management extensions for that single reason. Exposing the credentials, even in a masked state of a variable, is a security concern that they can't get past.

**Comment by jabbera** [comment]
The new build agent is based on Core CLR which has recently added NTLM support. It's documented as working to authenticate against TFS, I'm hoping this means it will also have that ability against deployment targets. If it does not we will be using a password manager API to retrieve the passwords during a release. (This appeased our security czar)

https://github.com/Microsoft/vsts-agent/issues/150
https://github.com/dotnet/corefx/pull/6905

**Comment by mvvsubbu** [comment]
We have a backlog item for this, so I am closing this issue. We will update you once this feature is done.

**Comment by jshepler** [comment]
It's been quite some time, any news?

**Comment by RoopeshNair** [comment]
@jshepler - we have pull-agent-based deployment in private beta. More info here https://blogs.msdn.microsoft.com/visualstudioalm/2016/12/05/agent-based-deployment-in-release-management/

IIS task in agent-based deployment doesn't rely on WinRM as it is running locally on the machine. 
Let me know if you are interested in trying out and provide us feedback.

Thanks,

**Comment by jshepler** [comment]
I'm not interested in having an agent on every server, that's not very practical. We have a single agent that deploys to various web servers. The current IIS deployment task has **required fields for admin creds**, which is what this (and #59 ) is about. The agent should be able to deploy to servers via "integrated" (NTLM) authentication - using the identity the agent is running as.

I'm still using the old IIS deployment task that doesn't have those fields as required. I don't understand why this request is so hard to understand or implement.

**Comment by RoopeshNair** [comment]
@jshepler I'm sorry for the issues you are facing, we do have plans to support multiple authentication schemes in the WinRM tasks. However, it will be a while before we can get to it. (>6months due to current priorities).
