### ISSUE TITLE
Version 1.136.0 of TFSAfRM can no longer retrieve External TFS Builds

### ISSUE THREAD

**Issue by ruairiohagan** [Microsoft/vsts-rm-extensions#455]
Hi,

The above version of TFS artifacts for Release Management can no longer connect to an external TFS instance to retrieve a list of build artifacts.

We are running multiple On Prem installations of TFS in separate domains, all running version 15.117.26714.0.

When using v 15.136.0 of TFSAfRM, if you test the connection endpoint from the services tab the connection is verified, but if you create a new artifact link in a release, it can get the list of projects from the remote TFS instance, but it can't get a list of build definitions. Also, if you try to create a release for an existing release definition, it cannot retrieve a list of builds from the remote instance.

We (luckily) have a vsix install file for TFSAfRM v15.106.2 and when that is installed on the same server we can get the list of build definitions and builds without any issues.

Also, because TFS now does automatic updates of the extensions this is being broken automatically every night as it goes off and retrieves the latest (broken) version from your servers. Any way of disabling that would be a good interim work around for this issue.

Thanks,

Ruairi.

**Comment by romil07** [comment]
@ruairiohagan 
Hi Ruairi, can you please let me know the number of build definitions that you have?

**Comment by romil07** [comment]
Hi @ruairiohagan Thanks for informing that.
We are in the process of rolling out a fix for this. This should be out early next week.
Request you to please wait till that. I will update this thread immediately as the fix is out.

Thanks

**Comment by ruairiohagan** [comment]
Hi @romil07 ,

We have just download version 15.138.0 of TFSAfRM from the marketplace and we're still getting issues.

We are now able to create a new release and select a build version from the remote TFS instance, but if we try to create a new release definition and try to select the build definition from the remote instance, it is still unable to retrieve the list of build definitions from the remote TFS.

Is there anything else we need to do other than reinstalling the latest version of the extension to get this to work?

Thanks!

**Comment by romil07** [comment]
Hi @ruairiohagan 
Can you check this with the latest version which 15.138.1
We updates it yesterday only and you should be unblocked with this update. Please check and update me here.

Thanks

**Comment by ruairiohagan** [comment]
Hi @romil07 ,

We've checked the latest update and it's working fine now, many thanks!
