### ISSUE TITLE
IIS Web App Deployment On Premise TFS Task Issue with ASP.NET Core 1.0 RC2

### ISSUE THREAD

**Issue by gencebay** [Microsoft/vsts-rm-extensions#51]
Trying to  IIS Web App Deployment Using WinRM for ASP.NET Core 1.0 RC2 on premise TFS Update 2.1 and latest vsts-rm extensions installed (1.1.0) but I'm getting this error :
_" Source does not support parameter called 'IIS Web Application Name'. Must be one of (). "_
on last release step.
I have created webdeploy package (as .zip file) properly but could not deploy it.
![deployment](https://cloud.githubusercontent.com/assets/879469/16199915/10e86668-3714-11e6-9a7d-04d710291c33.PNG)

**Comment by mvvsubbu** [comment]
In your webdeploy package there will be a file called parameters.xml which will contain IIS Web Application Name key that is missing in your case. Can you check do have that or not.

**Comment by gencebay** [comment]
Yes, it worked fine now! Thanks.

**Comment by mvvsubbu** [comment]
Ok I am closing the issue.
