### ISSUE TITLE
Using -enableRule:AppOffline stops msdeploy from creating the folder on disk

### ISSUE THREAD

**Issue by AHoran** [Microsoft/vsts-rm-extensions#54]
WinRM - IIS Web App Deployment

If you're deploying a new site, and the physical folder doesn't exist then msdeploy will create that folder for you and deploy the site into it.
However if you use -enableRule:AppOffline then you get this error

`Error: Could not find a part of the path 'C:\inetpub\wwwroot\MyProjectName\App_Offline.htm'`

My RM deployment will create an environment and site if none exists, otherwise it updates the existing. This makes it tricky to have a single script that does it all. As a workaround I've had to add a powershell task to create the folder if required.

**Comment by mvvsubbu** [comment]
Thanks for reporting we will address this

**Comment by mvvsubbu** [comment]
We have fixed this, we are creating folder upfront so this should happen
