### ISSUE TITLE
Deploy to App under existing Site

### ISSUE THREAD

**Issue by swcarter007** [Microsoft/vsts-rm-extensions#56]
I am trying to deploy to an application that exists under an existing site, but the deploy task doesn't seem to allow the ability to do that. Whenever I tried to set the WebsiteName to be the application name, it says site does not exist. Whenever I tried to set the WebsiteName to be the main website name, it overrides that website instead of creating a subfolder.

**Comment by mvvsubbu** [comment]
If you have website already created in your deployment task, you can give website name as website\application. Refer the below screen shot
![image](https://cloud.githubusercontent.com/assets/11993108/16565286/f183fc30-4229-11e6-9316-78f34d0114e5.png)

If you need to create website as well in management task give website name only.

**Comment by swcarter007** [comment]
I am attempting to create/update an application under a site, and that is what is failing currently.  I have the site created as Site1 and the app under it as App1.  In the Manage task, I used the WebsiteName field as "Site1\App1" and I pointed the physical path to "Site1\App1 Subfolder" and listed the port as the same port as Site1.  When I attempted this, I recieved an invalid site name error.

**Comment by mvvsubbu** [comment]
In manage task you should give site name as Site1 only. In deploy task you can specify the App1 details like I showed above

**Comment by swcarter007** [comment]
So I would have 3 tasks total.  1 Task to create the website, and 2 tasks one for deploying the site and one for the sub application?

**Comment by swcarter007** [comment]
I attempted this and it does indeed work.  My apologies for not testing that before my last comment.  Thank you for your assistance.

**Comment by kishoreinvits** [comment]
I am able to get this scenario to work as recommended.
I created two tasks 
1. For website creation(Say RMOWebsite)
![image](https://cloud.githubusercontent.com/assets/6522155/16694425/c1bdc4fa-4557-11e6-90d0-c563662af2ea.png)

2. For Web App creation(Say RMOWebsite\RMOWebApp) 
![image](https://cloud.githubusercontent.com/assets/6522155/16694459/05710284-4558-11e6-895b-3f5709cbe1a7.png)

Variables I Used
![image](https://cloud.githubusercontent.com/assets/6522155/16694489/387b87bc-4558-11e6-8571-b78cd433717d.png)

Hope this helps!
