### ISSUE TITLE
Support for appOfflineTemplate

### ISSUE THREAD

**Issue by mjacobs80** [Microsoft/vsts-rm-extensions#58]
I posted a review asking about such support, the response was that this could be done using the advanced arguments.

[https://ms-devlabs.gallery.vsassets.io/items?itemName=ms-vscs-rm.iiswebapp](url)

However, I am unclear as to how exactly that can be accomplished as the appOfflineTemplate option is part of the -dest argument for msdeploy.

If this can be achieved via the advanced parameters please provide an example.

**Comment by mvvsubbu** [comment]
Ok we got the problem. We will add this to our backlog. We are happy to take your contribution if you could do it or for now you can follow the below post and modify the existing task then upload to your account.

http://forums.iis.net/t/1203305.aspx?appOfflineTemplate+with+iis+handler

**Comment by jdshkolnik** [comment]
Would this solve the "##[error]System.Exception: Error Code: ERROR_FILE_IN_USE" I keep getting when I try to deploy to my on-prem IIS server? I can't seem to get around it.

**Comment by mvvsubbu** [comment]
Yes take app offline option should solve this problem

**Comment by jdshkolnik** [comment]
@mvvsubbu Any sense as to when this might get released assuming no external contributors?

**Comment by mvvsubbu** [comment]
AppOffline option is already available(under advanced) but not with custom template, Adding our PM/Lead to comment on timeline

**Comment by RoopeshNair** [comment]
We have added this to our backlog. However it will be 2-3 sprints before we can get to it.
As we are tracking this on our backlog, closing the issue
Thanks,
Roopesh Nair

**Comment by devingoble** [comment]
Any updates on where this is in the backlog?
