### ISSUE TITLE
Support for pass-through authentication?

### ISSUE THREAD

**Issue by peder** [Microsoft/vsts-rm-extensions#59]
![image](https://cloud.githubusercontent.com/assets/1018574/17192185/ff7ea164-5412-11e6-842a-8bd6ae8d4000.png)

If I use passwords in Build or Release scripts, I cannot change the password centrally with tools like Secret Server or Cyber-Ark Password Vault. Basically, this tool requires a never-changing password with admin rights to production servers. Is there any way around this?

**Comment by jabbera** [comment]
We all want this feature:

https://github.com/Microsoft/vsts-rm-extensions/issues/44

**Comment by peder** [comment]
Oh, my bad, I looked at the open issues for duplicate but not closed ones.

**Comment by jabbera** [comment]
No worries. Keep bringing it up. I'm dying for this feature

**Comment by mvvsubbu** [comment]
we have pull-agent-based deployment in private beta. More info here https://blogs.msdn.microsoft.com/visualstudioalm/2016/12/05/agent-based-deployment-in-release-management/
IIS task in agent-based deployment doesn't rely on WinRM as it is running locally on the machine. 
Let me know if you are interested in trying out and provide us feedback.

**Comment by RoopeshNair** [comment]
@peder, As @mvvsubbu  mentioned above, agent-based deployment is currently in private preview and is expected to be available around 2017 Update 2 time line. 

We have IIS deployment task which works with agent credentials. In case you are interested to participate in private beta, please drop me a note (roopesh dot nair at microsoft dot com)

Thanks
