### ISSUE TITLE
MsDeploy arguments and string concatentation

### ISSUE THREAD

**Issue by swcarter007** [Microsoft/vsts-rm-extensions#61]
There is an issue when adding additional arguments to the MsDeploy task for the Application Deployment task.  When you include things such as **-skip:Directory="\\logs$"**, it ends up writing the statement that is executed as  **-skip:Directory=** which ends up skipping all files from being updated.  The task itself should be changed so that quotation characters are accepted in case you need to specify a file that contains spaces and thus you need the quotation character to designate the full string.

**Comment by niadak** [comment]
This issue has been fixed and is available in latest version.
