### ISSUE TITLE
Given binding already exists for a different website

### ISSUE THREAD

**Issue by jfilburn** [Microsoft/vsts-rm-extensions#74]
Hello,

Setting bindings is failing with version 1.2.2.

I get this error:
Given binding already exists for a different website (web site 2 in this example), change the port and retry the operation.

I have a web site that has multiple bindings, for example:
Web site 1:
Bindings: app | app.domain.com | app.na.domain.com

Web site 2:
Bindings: appsvc | appsvc.domain.com | appsvc.na.domain.com

Deployment fails saying that the binding "app" already exists for web site 2 "appsvc"

For security purposes I made this example generic. I hope you can fix this so I don't have to run appcmd.exe by other means. I love the extension btw :-)

Wouldn't we use an exact match comparer rather than contains here?

Source code:
	elseif($site.Contains($binding))
	{
	throw "Given binding already exists for a different website (`"$site`"), change the port and retry the operation."
	}

Thanks,
Jeremy

**Comment by mvvsubbu** [comment]
Thanks for reporting the issue, we will fix it soon. BTW we are accepting contributions if you have fix you can provide we are more than happy to take it :)

**Comment by jfilburn** [comment]
I noticed that bindings are always listed ending with a comma ','
To fix it I would edit the  Extensions / IISWebAppDeploy / Src / Tasks / IISWebAppMgmt / AppCmdOnTargetMachines.ps1 function Does-BindingExists

I would change:
$binding = [string]::Format("{0}/{1}:{2}:{3}", $protocol, $ipAddress, $port, $hostname)

to
$binding = [string]::Format("{0}/{1}:{2}:{3},", $protocol, $ipAddress, $port, $hostname)

Adding the comma at the end of the string would prevent it from mistaken another binding that starts with the same string.

**Comment by jfilburn** [comment]
Update ...
Being new here I found I can make the change. I made the edit and created a pull request for this fix.

Thanks
Jeremy

**Comment by mvvsubbu** [comment]
Issue is fixed will be available in next release
